[workspace]
members=[
    "hello_world",
    "guessing_game",
    "common_programming_concepts",
    "ownership",
    "structs",
    "enums_pattern_matching",
    "common_collection",
    "error_handling",
]